version: '3'
services:
  frontend-dev:
    build:
      dockerfile: frontend.dockerfile
    volumes:
      - ./src:/code/src
      - ./fonts:/code/fonts
      - ./public:/code/public
    ports:
      - 3000:3000

  backend-dev:
    build:
      dockerfile: backend.dockerfile
    volumes:
      - ./public:/code/dist
      - /code/dist/vendor
    ports:
      - 8000:8000
    command: ["php", "-S", "0.0.0.0:8000", "-t", "public/"]
