name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Add web remote origin
        run: git remote add heroku https://heroku:${{ secrets.HEROKU_API_TOKEN }}@git.heroku.com/codium-web.git
      - name: Deploy Web to Heroku
        run: git push heroku `git subtree split --prefix heroku master`:refs/heads/master --force

